### ISSUE TITLE
Old/saved Card gets charged on Stripe 

### ISSUE THREAD

**Issue by psahalot** [zeen101/leaky-paywall#5] opened 2016-12-28 11:38 UTC
I have been using Leaky Paywall on a client site and I noticed that, even when I enter my new card details to the checkout form, my old card gets charged. 
Here's how to replicate it
1. Subscribe for a plan with Card 1. 
2. Subscribe to a new plan and it asks for the card details.
3. Enter Card 2 details in Stripe's checkout form
4. Click the Pay button. 

I checked my card statement and found that my Card 1 was charged instead of Card 2. 

Any ideas if this is an issue within the plugin or is it something to do with Stripe API?

**Comment by samueldjack** [comment] 2018-10-26 11:12
I've just come across this issue too, and I can see that the problem is with the Leaky Paywall code.

It occurs just [here](https://github.com/zeen101/leaky-paywall/blob/f92b7a6318c527d5d7bb1bf57fb521d3f91e6d3d/include/gateways/class-leaky-paywall-payment-gateway-stripe.php#L188):

				// Create a Customer
				if ( empty( $cu ) ) {
					$cu = \Stripe\Customer::create( $customer_array );
				} else {
					$cu->sources->create( array( 'source' => $_POST['stripeToken'] ) );
				}
				
				$charge_array = array(
					'customer'    => $cu->id,
					'amount'      => number_format( $this->amount, 2, '', '' ),
					'currency'    => apply_filters( 'leaky_paywall_stripe_currency', strtolower( $this->currency ) ),
					'description' => $this->level_name,
				);
				$charge = \Stripe\Charge::create( apply_filters( 'leaky_paywall_process_stripe_payment_charge_array', $charge_array ) );

The problem is that in the call to create a Stripe Charge, no `source` argument is passed in. According to the [Stripe documentation](https://stripe.com/docs/sources/customers) this means that the customer's default card will be used, usually the first one it was created with.

The following code appears to fix the problem in my limited testing:

				$sourceId = '';

				// Create a Customer
				if ( empty( $cu ) ) {
					$cu = \Stripe\Customer::create( $customer_array );
					$sourceId = $cu->default_source;
				} else {
					$source = $cu->sources->create( array( 'source' => $_POST['stripeToken'] ) );
					$sourceId = $source->id;
				}
				
				$charge_array = array(
					'customer'    => $cu->id,
					'amount'      => number_format( $this->amount, 2, '', '' ),
					'currency'    => apply_filters( 'leaky_paywall_stripe_currency', strtolower( $this->currency ) ),
					'description' => $this->level_name,
					'source' 	  => $sourceId
				);

Would it be possible for others to confirm this code works, and for it to be merged in?

**Closed** 2018-11-01 22:04 UTC
